name: Build and test

# Run the jobs for pushes and pull requests targetting main branch.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Build and test project.
  linux-build:
    strategy:
      matrix:
        build:
          - 1
        include:
          - build: 1
            build-type: Release
            build-tests: 'ON'
            build-docs: 'ON'
    name: 'Ubuntu 18.04
      <type=${{ matrix.build-type }},
       tests=${{ matrix.build-tests }},
       docs=${{ matrix.build-docs }}>'
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies (Linux)
        run: sudo apt-get install cmake doxygen graphviz
      - uses: actions/checkout@v2
      - name: Create build directories
        run: |
          mkdir _build
          mkdir _install
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -DBUILD_TESTING=${{ matrix.build-tests }} \
                -DBUILD_DOCUMENTATION=${{ matrix.build-docs }} \
                -DCMAKE_INSTALL_PREFIX=../_install \
                ..
        working-directory: _build
      - name: Build
        run: |
          cmake --build . \
                --verbose \
                --target install \
                --config ${{ matrix.build-type }}
        working-directory: _build
      - name: Test
        run: ctest -VV --output-on-failure -C ${{ matrix.build-type }}
        working-directory: _build

  windows-build:
    strategy:
      matrix:
        build:
          - 1
        include:
          - build: 1
            build-type: Release
            build-tests: 'ON'
            build-docs: 'OFF'
    name: 'Windows 2019 
      <MSVC 16.4 
       type=${{ matrix.build-type }}, 
       tests=${{ matrix.build-tests }}, 
       docs=${{ matrix.build-docs }}>'
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Create build directories
        run: |
          mkdir _build
          mkdir _install
        shell: bash
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -DBUILD_TESTING=${{ matrix.build-tests }} \
                -DBUILD_DOCUMENTATION=${{ matrix.build-docs }} \
                -DCMAKE_INSTALL_PREFIX=../_install \
                ..
        shell: bash
        working-directory: _build
      - name: Build
        run: |
          cmake --build . \
                --verbose \
                --target install \
                --config ${{ matrix.build-type }}
        shell: bash
        working-directory: _build
     #- name: Test
     #  run: ctest -VV --output-on-failure -C ${{ matrix.build-type }}
     #  shell: bash
     #  working-directory: _build

  macos-build:
    strategy:
      matrix:
        build:
          - 1
        include:
          - build: 1
            build-type: Release
            build-tests: 'ON'
            build-docs: 'OFF'
    name: 'Mac OSX 10.15
      <type=${{ matrix.build-type }}, 
       tests=${{ matrix.build-tests }}, 
       docs=${{ matrix.build-docs }}>'
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Create build directories
        run: |
          mkdir _build
          mkdir _install
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -DBUILD_TESTING=${{ matrix.build-tests }} \
                -DBUILD_DOCUMENTATION=${{ matrix.build-docs }} \
                -DCMAKE_INSTALL_PREFIX=../_install \
                 .. \
        working-directory: _build
      - name: Build
        run: |
          cmake --build . \
                --verbose \
                --target install \
                --config ${{ matrix.build-type }}
        working-directory: _build
      - name: Test
        run: ctest -VV --output-on-failure -C ${{ matrix.build-type }}
        working-directory: _build
